import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const root=process.cwd();const port=Number(process.env.PORT||4173);const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.pdf':'application/pdf','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.txt':'text/plain; charset=utf-8','.xml':'application/xml; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8'};
async function send(res,status,body,type='text/plain; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(body)}
async function serveFile(res,pathname){const aliases={'/':'index.html','/pdf':'pdf.html','/pdf/':'pdf.html','/reader':'reader.html','/reader/':'reader.html'};const relative=aliases[pathname]||pathname.replace(/^\//,'');const target=path.resolve(root,relative);if(!target.startsWith(root)||!existsSync(target))return send(res,404,'Not found');try{const body=await readFile(target);send(res,200,body,mime[path.extname(target).toLowerCase()]||'application/octet-stream')}catch{send(res,500,'Unable to read file')}}
const server=createServer(async(req,res)=>{try{const requestUrl=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(requestUrl.pathname==='/api/pdf'){const target=requestUrl.searchParams.get('url');if(!target||!/^https?:$/.test(new URL(target).protocol))return send(res,400,'A valid HTTP PDF URL is required.');const upstream=await fetch(target,{redirect:'follow'});if(!upstream.ok)return send(res,upstream.status,`The PDF host returned ${upstream.status}.`);const type=upstream.headers.get('content-type')||'';if(type.includes('text/html'))return send(res,415,'The link returned a webpage, not a PDF file.');const body=Buffer.from(await upstream.arrayBuffer());if(body.length>60*1024*1024)return send(res,413,'PDF is larger than 60 MB.');return send(res,200,body,'application/pdf')}if(req.method!=='GET')return send(res,405,'GET only');return serveFile(res,decodeURIComponent(requestUrl.pathname))}catch(error){return send(res,500,error.message||'Server error')}});server.listen(port,()=>console.log(`ThunderStudy PDF running at http://localhost:${port}`));
